#!/bin/bash

# TODO usage document

set -e

readonly SHA1="$(git rev-parse HEAD)"
readonly SHA2="$(git rev-parse HEAD~1)"

check(){
  git diff "${SHA1}" "${SHA2}" --name-only | while read -r file; do
    echo "${file}"
    if [[ -f "${file}" ]]; then
      local first_line
      first_line="$(head -1 "${file}")"
      if [[ ("${first_line}" == *"#!/bin/bash"*) || ("${first_line}" == *"#!/bin/sh"*) ]]; then
        shellcheck "${file}"
      fi
    fi
  done
}

check